name = "dokimasia-articole"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "site-asociatie"

[vars]
EJS_SERVICE_ID  = "service_4a8gp1c"
EJS_TEMPLATE_ID = "template_wg7nlez"
EJS_PUBLIC_KEY  = "q9cxett"
